main page
Pasheza/boost_grade pull request #1
Opened 2022-04-09 19:08 UTC by Pasheza

2022-04-10 12:34 UTC, HazarD2311 requested changes

2022-04-10 12:34 UTC, HazarD2311 commented on lib/main.dart
> +        title: Text(widget.title, style: const TextStyle(color: Colors.black)),
Обрати внимание, там у текста есть тень в дизайне

2022-04-10 12:34 UTC, HazarD2311 commented on lib/main.dart
>  class MyHomePage extends StatefulWidget {
1. Попробуй продумать заранее иерархию виджетов по пакетам. Выдели стартовый экран в отдельный файл.
2. Сделай заготовки под навигацию и файлы под новые экраны
В будущем такая практика поможет более независимо разветвлять фичи и не связывать пулл реквесты при работе в команде

2022-04-10 12:34 UTC, HazarD2311 commented on lib/main.dart
> +        title: Text(widget.title, style: const TextStyle(color: Colors.black)),
Давай выделим в отдельные файлы переиспользуемые компоненты

Для меня привычен обычно такой набор, выбери нужные тебе:
- палитра цветов
- набор шрифтов
- текстовые ресурсы
- набор ассетов
- тема

2022-04-10 12:34 UTC, HazarD2311 commented on lib/main.dart
> +      onPressed: () {},
проверь форматирование файла, в будущем на проекте будут билды и если отсутствует форматирование - пулл реквест будет падать

2022-04-10 14:05 UTC, Pasheza commented on lib/main.dart
> +        title: Text(widget.title, style: const TextStyle(color: Colors.black)),
Я пытался через ThemeData сделать дефолтный черный цвет для текста и иконок как в дизайне, но так не понял как это сделать. Сейчас дефолтный цвет для текста - белый.

2022-04-10 14:05 UTC, Pasheza commented on lib/main.dart
> +        title: Text(widget.title, style: const TextStyle(color: Colors.black)),
Не вижу в фигме у текста тень, или ты что то другое имеешь ввиду?

2022-04-10 14:07 UTC, Pasheza commented on lib/main.dart
>  class MyHomePage extends StatefulWidget {
Выделю в отдельный файл начальную страницу. Файлы под новые экраны будут в следующих ПР.

2022-04-10 14:24 UTC, Sanlovty commented on lib/main.dart
> +        title: Text(widget.title, style: const TextStyle(color: Colors.black)),
@Pasheza там на главной страничке, в эпп баре в фигме у слова "Главная" тень присутствует

2022-04-10 14:27 UTC, Pasheza commented on lib/main.dart
> +        title: Text(widget.title, style: const TextStyle(color: Colors.black)),
Выделю в отдельный файл цвет.

2022-04-10 14:27 UTC, Pasheza commented on lib/main.dart
> +        title: Text(widget.title, style: const TextStyle(color: Colors.black)),
Не заметил сразу, исправлю.

2022-04-10 14:28 UTC, Pasheza commented on lib/main.dart
> +      onPressed: () {},
Исправлю.

2022-04-12 10:33 UTC, HazarD2311 commented on lib/main.dart
> +        title: Text(widget.title, style: const TextStyle(color: Colors.black)),
ну тут есть много вариантов:
1. создать свой экземпляр ThemeData и прокинуть в `MaterialApp`. Там как раз, если изучить подробнее, есть набор стилей для текстов и кнопок. Дока может тебе в этом https://api.flutter.dev/flutter/material/TextTheme-class.html
2. сделать на подобие цветов статический набор и со стилями. Например: `TextStyles.придумайНазваниеBlack`
3. Можно ещё локально обернуть в `Theme` эта тема будет работать только для его `child`

я предпочитаю 1 и 2 вариант в совокупности

2022-04-12 10:39 UTC, HazarD2311 requested changes

2022-04-12 10:39 UTC, HazarD2311 commented on lib/home_page.dart
> +class MyHomePage extends StatefulWidget {
Подскажи, почему решил сделать Stateful, а не Stateless например

2022-04-12 10:39 UTC, HazarD2311 commented on lib/home_page.dart
> +        onPressed: () {},
рекомендую всегда вверху конструктора держать однострочные параметры, потом многострочные и только потом `child`

2022-04-12 10:39 UTC, HazarD2311 commented on lib/home_page.dart
> +            MainPageButton(title: '4 квадрата'),
давай ещё строки отдельно выделим

2022-04-12 10:39 UTC, HazarD2311 commented on lib/colors.dart
> +import 'package:flutter/material.dart';
Довольно часто будет приходиться делать такие базовые ПРы перед стартов фичи, чтобы потом можно было командой без будущих гит-конфликтов продолжать реализацию фичи.

В рамках задания это, конечно, необязательно:
но давай попробуем продумать заранее структуру пакетов, чтобы потом без лишних изменений можно было дополнять новые экраны.
Попробуй ответить на следующие вопросы для себя:
- в какую папку ты положишь `Util` классы
- куда положишь остальные 5 экранов
- где будут лежать модели
- где будут лежать сервисы

2022-04-12 10:39 UTC, HazarD2311 commented on lib/main.dart
> +        title: Text(widget.title, style: const TextStyle(color: Colors.black)),
везде где у тебя присутствует `const TextStyle(...)` - давай заменим на один из первых двух вариантов

2022-04-12 19:54 UTC, Pasheza commented on lib/home_page.dart
> +class MyHomePage extends StatefulWidget {
Может быть Stateful, исправлю.

2022-04-12 19:55 UTC, Pasheza commented on lib/home_page.dart
> +        onPressed: () {},
Ок, понял, исправлю

2022-04-12 21:49 UTC, Pasheza commented on lib/colors.dart
> +import 'package:flutter/material.dart';
Да, я понял концепцию, в данном случае проще это добавлять по мере необходимости.

2022-04-12 21:53 UTC, Pasheza commented on lib/main.dart
> +        title: Text(widget.title, style: const TextStyle(color: Colors.black)),
Довольно странно, оставил ThemeData полностью дефолтным, но при этом цвет изменяется при вызове из контекста по типу, а по дефолту остается белым.
          ```Icon(
              Icons.arrow_forward_outlined,
              color: Theme.of(context).iconTheme.color,
            )```

2022-04-12 21:54 UTC, Pasheza commented on lib/home_page.dart
> +            MainPageButton(title: '4 квадрата'),
Выделил

2022-04-15 11:49 UTC, HazarD2311 approved these changes

2022-04-15 13:03 UTC, merged